namespace Kentico.Xperience.Twilio.SendGrid
{
    /// <summary>
    /// Constants used in the SendGrid integration.
    /// </summary>
    public static class SendGridConstants
    {
        /// <summary>
        /// UniGrid mass action key for deleting Xperience bounces.
        /// </summary>
        public const string ACTION_DELETE_XPERIENCE_BOUNCE = "kx-bounce";


        /// <summary>
        /// UniGrid mass action key for deleting SendGrid bounces.
        /// </summary>
        public const string ACTION_DELETE_SENDGRID_BOUNCE = "sg-bounce";


        /// <summary>
        /// The API key for using the SendGrid API.
        /// </summary>
        public const string APPSETTING_API_KEY = "SendGridApiKey";


        /// <summary>
        /// A key generated by SendGrid to verify the source of a webhook POST.
        /// </summary>
        public const string APPSETTING_WEBHOOK_KEY = "SendGridWebhookVerificationKey";


        /// <summary>
        /// The cache key used to store the response from SendGrid's Bounce API listing.
        /// </summary>
        public const string CACHE_KEY_BOUNCES = "SendGrid|API|Bounces";


        /// <summary>
        /// The key of the header storing the SendGrid webhook signature.
        /// </summary>
        public const string HEADER_WEBHOOK_SIGNATURE = "X-Twilio-Email-Event-Webhook-Signature";


        /// <summary>
        /// The key of the header storing the SendGrid webhook timestamp.
        /// </summary>
        public const string HEADER_WEBHOOK_TIMESTAMP = "X-Twilio-Email-Event-Webhook-Timestamp";


        /// <summary>
        /// The virtual URL of the suppression management mass action modal window.
        /// </summary>
        public const string URL_SUPPRESSION_MASSACTION = "~/CMSModules/Kentico.Xperience.Twilio.SendGrid/Pages/SuppressionManagementMassAction.aspx";
    }
}